[package]
name = "pdf_modify"
version = "0.1.0"
edition = "2024"
default-run = "pdf_modify"

[dependencies]
anyhow = "1.0.98"
hex = "0.4.3"
image = { version = "0.25.6", default-features = false, features = ["png"] }
lopdf = "0.34.0"
openssl = "0.10.72"
